#!/bin/sh

cd "$(dirname "$0")"

lock() {
  grim -t jpeg - | convert -  -blue-shift 0.5 -scale 20% -blur 0x2.5 -resize 500% /tmp/mylock.jpeg
  swaylock -i /tmp/mylock.jpeg
}

case "$1" in
  lock)
    lock
    ;;
  logout)
    i3-msg exit
    ;;
  suspend)
    lock && systemctl suspend
    ;;
  hibernate)
    lock && systemctl hibernate
    ;;
  reboot)
    systemctl reboot
    ;;
  shutdown)
    systemctl poweroff
    ;;
  *)
    echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
    exit 2
esac
                                                                                                                                                
exit 0
